# -*- coding: utf-8 -*-
"""Analisis_Sentimen_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtAxgbnwwpQqa8i9TGRYp2XcbxMn1R5K

# Crawl Data Twitter > 2000 Tweets
The crawling process was done using Tweet-Harvest. Written by Helmi Satria on  March 30th 2024.
"""

#@title Twitter Auth Token

twitter_auth_token = 'e20bd5d33bd1136dc74d65a3d9371a7c0de5a5cf' # change this auth token

!apt-get update
!apt-get install -y \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxrandr2 \
  libgbm1 \
  libpangocairo-1.0-0 \
  libpango-1.0-0 \
  libasound2 \
  libnss3 \
  libxshmfence1 \
  libgtk-3-0

# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

# Crawl Data

filename = 'cerai.csv'
search_keyword = 'cerai since:2024-11-01 until:2025-11-01 lang:id'
limit = 2000

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd

df_crawl = pd.read_csv('cerai.csv')

print("Jumlah tweet hasil crawling:", len(df_crawl))

# Load data hasil crawling
df_crawl = pd.read_csv('cerai.csv')

# Pilih kolom yang relevan untuk skripsi
tabel_crawling = df_crawl[['created_at', 'user_id_str', 'full_text', 'lang']].head(10)

# Tampilkan tabel
tabel_crawling

"""Instal sastrawi"""

!pip install Sastrawi

import nltk
nltk.download('punkt')

# ===============================
# IMPORT & DOWNLOAD NLTK
# ===============================
import pandas as pd
import re
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download('punkt')
nltk.download('punkt_tab')   # 🔴 WAJIB untuk Python 3.12
nltk.download('stopwords')

import pandas as pd

"""## **PRE-PROCESSING**"""

# =====================================================
# IMPORT LIBRARY
# =====================================================
import os, re, string
import pandas as pd
import numpy as np
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# =====================================================
# LOAD DATA
# =====================================================
df = pd.read_csv('cerai.csv')   # kolom: full_text, created_at
df = df[['created_at', 'full_text']].dropna()
print("Jumlah tweet:", len(df))

# pastikan format datetime
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

# =====================================================
# 1. CLEANSING
# =====================================================
emoji_map = {
    "😂": " bahagia ", "🤣": " bahagia ", "😊": " senang ", "😍": " cinta ",
    "😢": " sedih ", "😭": " sedih ", "😡": " marah ", "😠": " marah ",
    "😞": " kecewa ", "😔": " sedih ", "❤️": " cinta ", "💔": " patah "
}

def cleansing(text):
    text = str(text)
    for emo, word in emoji_map.items():
        text = text.replace(emo, word)
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df['cleansed'] = df['full_text'].apply(cleansing)

# =====================================================
# 2. CASE FOLDING
# =====================================================
df['case_folding'] = df['cleansed'].str.lower()

# =====================================================
# 3. TOKENIZATION
# =====================================================
df['tokenized'] = df['case_folding'].apply(lambda x: word_tokenize(x))

# =====================================================
# 4. STOPWORD REMOVAL (NEGASI DIPERTAHANKAN)
# =====================================================
stopwords_id = set(stopwords.words("indonesian"))

negation_words = {"tidak","bukan","jangan","tak","gak","ga","nggak"}

stopwords_tambahan_domain = {
    "banget","orang","udah","kalo","dah","nya","tau","si","pas","sampe",
    "krn","tu","tuh","klo","sm","emang","ni","kaya","amp","kak","nak",
    "kali","gin","gitu","bilang","karna","jd","kayak","jg","wkwk",
    "lg","skrg","ku","la","kek","gt","dr","to","x","eh","i","gimana",
    "mending","blm","lo","je","iya","dikit","ken","temen","ex","suruh",
    "pake","mulu","doang","kah","loh","mah","kyk","asa","s",
    "sabrina","deddy","corbuzier","chairunnisa","raisa","hamish",
    "andre","erin","adly","fairuz","rishi","angbeen","taulany","daud",
    "yg", "sih"
}

stopwords_final = (stopwords_id | stopwords_tambahan_domain) - negation_words

df['no_stopwords'] = df['tokenized'].apply(
    lambda tokens: [w for w in tokens if w not in stopwords_final]
)


# =====================================================
# 5. STEMMING
# =====================================================

stemmer = StemmerFactory().create_stemmer()

def stemming(tokens):
    return [stemmer.stem(w) for w in tokens]

df['stemmed'] = df['no_stopwords'].apply(stemming)

# =====================================================
# FINAL TEXT (UNTUK MODEL)
# =====================================================
df['preprocessed_text'] = df['stemmed'].apply(lambda x: " ".join(x))
# JANGAN overwrite kolom
df = df[df['preprocessed_text'].str.split().str.len() >= 3].reset_index(drop=True)

# df = df[df['preprocessed_text'].str.split().str.len() >= 3]

# =====================================================
# SIMPAN HASIL
# =====================================================
df[['full_text','created_at','cleansed','case_folding','tokenized','no_stopwords','stemmed','preprocessed_text']].head()
df.to_csv('cerai_preprocessing_lengkap.csv', index=False)
print("✅ File disimpan: cerai_preprocessing_lengkap.csv")

# =====================================================
# TABEL CONTOH HASIL PRE-PROCESSING (5 DATA)
# =====================================================

# Ambil 5 contoh tweet pertama
contoh = df[['full_text',
             'cleansed',
             'case_folding',
             'tokenized',
             'no_stopwords',
             'stemmed']].head(5)

# Ubah list token menjadi string agar rapi di tabel
contoh['tokenized'] = contoh['tokenized'].apply(lambda x: ", ".join(x))
contoh['no_stopwords'] = contoh['no_stopwords'].apply(lambda x: ", ".join(x))
contoh['stemmed'] = contoh['stemmed'].apply(lambda x: ", ".join(x))

# Tampilkan tabel
import pandas as pd

df_cleansed = pd.read_csv('cerai_preprocessing_lengkap.csv')

# Load data hasil crawling
df_cleansed = pd.read_csv('cerai_preprocessing_lengkap.csv')

# Pilih kolom yang relevan untuk skripsi
tabel_crawling = df_cleansed[['full_text', 'cleansed']].head(5)

tabel_crawling

import pandas as pd
pd.set_option('display.max_colwidth', None)

# Load the preprocessed data to recreate tabel_crawling
df_cleansed = pd.read_csv('cerai_preprocessing_lengkap.csv')

# Select relevant columns for tabel_crawling
# tabel_crawling = df_cleansed[['full_text', 'cleansed']].head(5)
# tabel_crawling = df_cleansed[['full_text', 'case_folding']].head(5)

# tabel_crawling = df_cleansed[['full_text', 'tokenized']].head(5)
# tabel_crawling = df_cleansed[['full_text', 'no_stopwords']].head(5)
tabel_crawling = df_cleansed[['full_text', 'stemmed']].head(5)
# Display the table with widened columns
display(tabel_crawling)

# =====================================================
# KODE FINAL LENGKAP: ANALISIS SENTIMEN TWEET PERCERAIAN
# Perbandingan MultinomialNB vs GaussianNB + Visualisasi
# =====================================================

# =====================================================
# 1. IMPORT LIBRARY (DIPERBAIKI)
# =====================================================
import os, re, string
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    f1_score,
    recall_score,
    precision_score,
    confusion_matrix
)
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.preprocessing import FunctionTransformer
import pickle
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.pyplot as plt
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling import SMOTE


import warnings
warnings.filterwarnings('ignore')

# NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# =====================================================
# 2. LOAD DATA
# =====================================================
print("=" * 70)
print("LOAD DATA")
print("=" * 70)

df = pd.read_csv('cerai_preprocessing_lengkap.csv')
print(f"Kolom tersedia: {df.columns.tolist()}")
print(f"Jumlah data: {len(df)}")

df = df.dropna(subset=['preprocessed_text'])
print(f"Jumlah data setelah hapus NaN: {len(df)}")

# =====================================================
# 3. AUTO LABELING DENGAN TEXTBLOB
# =====================================================
print("\n" + "=" * 70)
print("AUTO LABELING DENGAN TEXTBLOB")
print("=" * 70)

def label_sentiment(text):
    try:
        polarity = TextBlob(str(text)).sentiment.polarity
        return 'positif' if polarity > 0 else 'negatif'
    except:
        return 'negatif'

df['label'] = df['preprocessed_text'].apply(label_sentiment)

print(f"\nTotal data: {len(df)}")
print("\nDistribusi Sentimen:")
print(df['label'].value_counts())
print(f"\nRasio Negatif:Positif = {df['label'].value_counts()['negatif'] / df['label'].value_counts()['positif']:.1f}:1")

# =====================================================
# 4. SPLIT DATA
# =====================================================
print("\n" + "=" * 70)
print("SPLIT DATA")
print("=" * 70)

X = df['preprocessed_text']
y = df['label'].map({'positif': 1, 'negatif': 0})

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"Data Latih (Training): {len(X_train)} sampel ({len(X_train)/len(X)*100:.1f}%)")
print(f"Data Uji (Test): {len(X_test)} sampel ({len(X_test)/len(X)*100:.1f}%)")

# =====================================================
# 5. PARAMETER MODEL
# =====================================================
tfidf_params = {
    'max_features': 3000,
    'ngram_range': (1, 2),
    'min_df': 2,
    'max_df': 0.8
}
smote_params = {'random_state': 42}
nb_multinomial_params = {'alpha': 0.5}
nb_gaussian_params = {'var_smoothing': 1e-9}


# tambahan
# 1. Lihat Distribusi Asli (Sebelum SMOTE)
print("\n[Visualisasi] Distribusi Kelas Training (SEBELUM SMOTE):")
counter_before = Counter(y_train)
print(f"Counter: {counter_before}")

# 2. Simulasi Langkah Pipeline untuk Visualisasi
X_train_copy = X_train.copy() if hasattr(X_train, 'copy') else X_train
vectorizer_viz = TfidfVectorizer(**tfidf_params)
X_train_tfidf = vectorizer_viz.fit_transform(X_train_copy)

# Terapkan SMOTE pada data TF-IDF
smote_viz = SMOTE(**smote_params)
X_train_resampled, y_train_resampled = smote_viz.fit_resample(X_train_tfidf, y_train)

# 3. Lihat Distribusi Setelah SMOTE
print("\n[Visualisasi] Distribusi Kelas Training (SETELAH SMOTE):")
counter_after = Counter(y_train_resampled)
print(f"Counter: {counter_after}")

# 4. Plot Perbandingan (DIPERBAIKI)
plt.figure(figsize=(10, 6))
labels = ['Kelas 0 (Negatif)', 'Kelas 1 (Positif)']
counts_before = [counter_before[0], counter_before[1]]
counts_after = [counter_after[0], counter_after[1]]

x = range(len(labels))
width = 0.35

plt.bar([i - width/2 for i in x], counts_before, width, label='Sebelum SMOTE', color='red', alpha=0.7)
plt.bar([i + width/2 for i in x], counts_after, width, label='Setelah SMOTE', color='green', alpha=0.7)

plt.xlabel('Kelas')
plt.ylabel('Jumlah Data')
plt.title('Perbandingan Distribusi Kelas (Training Set)')
plt.xticks(x, labels)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# -----------------------------------------------------
# [ASLI] Pipeline Training
# -----------------------------------------------------
pipeline_mnb = ImbPipeline([
    ('tfidf', TfidfVectorizer(**tfidf_params)),
    ('smote', SMOTE(**smote_params)),
    ('nb', MultinomialNB(**nb_multinomial_params))
])

pipeline_mnb.fit(X_train, y_train)
y_pred_mnb = pipeline_mnb.predict(X_test)

print("\nEvaluasi MultinomialNB:")
print(classification_report(y_test, y_pred_mnb, target_names=['negatif', 'positif']))

acc_mnb = accuracy_score(y_test, y_pred_mnb)
f1_mnb = f1_score(y_test, y_pred_mnb, average='macro')
f1_pos_mnb = f1_score(y_test, y_pred_mnb, pos_label=1)
rec_mnb = recall_score(y_test, y_pred_mnb, pos_label=1)
prec_mnb = precision_score(y_test, y_pred_mnb, pos_label=1)

print(f"Accuracy: {acc_mnb:.4f}")
print(f"F1-Macro: {f1_mnb:.4f}")
print(f"F1-Positif: {f1_pos_mnb:.4f}")
print(f"Recall Positif: {rec_mnb:.4f}")
print(f"Precision Positif: {prec_mnb:.4f}")
# # =====================================================
# # 6. MODEL 1: MULTINOMIAL NAIVE BAYES
# # =====================================================
# print("\n" + "=" * 70)
# print("MODEL 1: MULTINOMIAL NAIVE BAYES")
# print("=" * 70)

# pipeline_mnb = ImbPipeline([
#     ('tfidf', TfidfVectorizer(**tfidf_params)),
#     ('smote', SMOTE(**smote_params)),
#     ('nb', MultinomialNB(**nb_multinomial_params))
# ])

# pipeline_mnb.fit(X_train, y_train)
# y_pred_mnb = pipeline_mnb.predict(X_test)

# print("\nEvaluasi MultinomialNB:")
# print(classification_report(y_test, y_pred_mnb, target_names=['negatif', 'positif']))

# acc_mnb = accuracy_score(y_test, y_pred_mnb)
# f1_mnb = f1_score(y_test, y_pred_mnb, average='macro')
# f1_pos_mnb = f1_score(y_test, y_pred_mnb, pos_label=1)
# rec_mnb = recall_score(y_test, y_pred_mnb, pos_label=1)  # ✅ Sekarang jalan
# prec_mnb = precision_score(y_test, y_pred_mnb, pos_label=1)  # ✅ Sekarang jalan

# print(f"Accuracy: {acc_mnb:.4f}")
# print(f"F1-Macro: {f1_mnb:.4f}")
# print(f"F1-Positif: {f1_pos_mnb:.4f}")
# print(f"Recall Positif: {rec_mnb:.4f}")
# print(f"Precision Positif: {prec_mnb:.4f}")

# =====================================================
# 7. MODEL 2: GAUSSIAN NAIVE BAYES
# =====================================================
print("\n" + "=" * 70)
print("MODEL 2: GAUSSIAN NAIVE BAYES")
print("=" * 70)

def sparse_to_dense(X):
    if hasattr(X, 'toarray'):
        return X.toarray()
    return X

pipeline_gnb = ImbPipeline([
    ('tfidf', TfidfVectorizer(**tfidf_params)),
    ('smote', SMOTE(**smote_params)),
    ('to_dense', FunctionTransformer(sparse_to_dense, validate=False)),
    ('nb', GaussianNB(**nb_gaussian_params))
])

pipeline_gnb.fit(X_train, y_train)
y_pred_gnb = pipeline_gnb.predict(X_test)

print("\nEvaluasi GaussianNB:")
print(classification_report(y_test, y_pred_gnb, target_names=['negatif', 'positif']))

acc_gnb = accuracy_score(y_test, y_pred_gnb)
f1_gnb = f1_score(y_test, y_pred_gnb, average='macro')
f1_pos_gnb = f1_score(y_test, y_pred_gnb, pos_label=1)
rec_gnb = recall_score(y_test, y_pred_gnb, pos_label=1)
prec_gnb = precision_score(y_test, y_pred_gnb, pos_label=1)

print(f"Accuracy: {acc_gnb:.4f}")
print(f"F1-Macro: {f1_gnb:.4f}")
print(f"F1-Positif: {f1_pos_gnb:.4f}")
print(f"Recall Positif: {rec_gnb:.4f}")
print(f"Precision Positif: {prec_gnb:.4f}")

# =====================================================
# 8. TABEL PERBANDINGAN
# =====================================================
print("\n" + "=" * 70)
print("TABEL PERBANDINGAN KINERJA MODEL")
print("=" * 70)

comparison_df = pd.DataFrame({
    'Metode': ['MultinomialNB', 'GaussianNB'],
    'Akurasi': [acc_mnb, acc_gnb],
    'F1-Score (Macro)': [f1_mnb, f1_gnb],
    'F1-Score (Positif)': [f1_pos_mnb, f1_pos_gnb],
    'Precision (+)': [prec_mnb, prec_gnb],
    'Recall (+)': [rec_mnb, rec_gnb]
})
print(comparison_df.to_string(index=False))

# =====================================================
# 9. VISUALISASI LENGKAP
# =====================================================
print("\n" + "=" * 70)
print("VISUALISASI")
print("=" * 70)

# Buat figure dengan 4 subplots
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. BAR CHART PERBANDINGAN MODEL
ax1 = axes[0, 0]
metrics = ['Accuracy', 'F1-Macro', 'F1-Positif', 'Precision+', 'Recall+']
mnb_vals = [acc_mnb, f1_mnb, f1_pos_mnb, prec_mnb, rec_mnb]
gnb_vals = [acc_gnb, f1_gnb, f1_pos_gnb, prec_gnb, rec_gnb]

x = np.arange(len(metrics))
width = 0.35

bars1 = ax1.bar(x - width/2, mnb_vals, width, label='Multinomial NB', color='#2E8B57', alpha=0.8)
bars2 = ax1.bar(x + width/2, gnb_vals, width, label='Gaussian NB', color='#DC143C', alpha=0.8)

ax1.set_ylabel('Skor', fontsize=12)
ax1.set_title('Perbandingan Performa Model', fontsize=14, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(metrics, fontsize=10)
ax1.legend(loc='upper right')
ax1.set_ylim(0, 1.1)
ax1.grid(axis='y', linestyle='--', alpha=0.5)

for bar in bars1:
    height = bar.get_height()
    ax1.annotate(f'{height:.3f}', xy=(bar.get_x() + bar.get_width()/2, height),
                xytext=(0, 3), textcoords="offset points", ha='center', fontsize=9)
for bar in bars2:
    height = bar.get_height()
    ax1.annotate(f'{height:.3f}', xy=(bar.get_x() + bar.get_width()/2, height),
                xytext=(0, 3), textcoords="offset points", ha='center', fontsize=9)

# 2. PIE CHART DISTRIBUSI SENTIMEN
ax2 = axes[0, 1]
sentiment_counts = df['label'].value_counts()
colors = ['#DC143C', '#2E8B57']
wedges, texts, autotexts = ax2.pie(sentiment_counts, labels=['Negatif', 'Positif'],
                                    autopct='%1.1f%%', colors=colors, startangle=90,
                                    explode=(0, 0.1))
ax2.set_title('Distribusi Sentimen\n(Data Asli)', fontsize=14, fontweight='bold')
for autotext in autotexts:
    autotext.set_fontsize(11)
    autotext.set_fontweight('bold')

# 3. CONFUSION MATRIX MULTINOMIAL NB
ax3 = axes[1, 0]
cm_mnb = confusion_matrix(y_test, y_pred_mnb)
sns.heatmap(cm_mnb, annot=True, fmt='d', cmap='Greens', ax=ax3,
            xticklabels=['Negatif', 'Positif'], yticklabels=['Negatif', 'Positif'],
            annot_kws={'size': 14}, linewidths=2, linecolor='white')
ax3.set_title('Confusion Matrix - Multinomial NB', fontsize=14, fontweight='bold')
ax3.set_ylabel('Aktual', fontsize=12)
ax3.set_xlabel('Prediksi', fontsize=12)

# 4. CONFUSION MATRIX GAUSSIAN NB
ax4 = axes[1, 1]
cm_gnb = confusion_matrix(y_test, y_pred_gnb)
sns.heatmap(cm_gnb, annot=True, fmt='d', cmap='Reds', ax=ax4,
            xticklabels=['Negatif', 'Positif'], yticklabels=['Negatif', 'Positif'],
            annot_kws={'size': 14}, linewidths=2, linecolor='white')
ax4.set_title('Confusion Matrix - Gaussian NB', fontsize=14, fontweight='bold')
ax4.set_ylabel('Aktual', fontsize=12)
ax4.set_xlabel('Prediksi', fontsize=12)

plt.tight_layout()
plt.savefig('perbandingan_model_lengkap.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ Gambar disimpan: perbandingan_model_lengkap.png")

# =====================================================
# 10. TIME SERIES VISUALIZATION
# =====================================================
if 'created_at' in df.columns:
    print("\n" + "=" * 70)
    print("TIME SERIES VISUALIZATION")
    print("=" * 70)

    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    df = df.dropna(subset=['created_at'])

    df['date'] = df['created_at'].dt.date
    daily_sentiment = df.groupby(['date', 'label']).size().unstack(fill_value=0)

    fig, ax = plt.subplots(figsize=(14, 6))
    daily_sentiment.plot(kind='line', ax=ax, marker='o', linewidth=2, markersize=6)
    ax.set_title('Distribusi Sentimen per Hari', fontsize=14, fontweight='bold')
    ax.set_xlabel('Tanggal', fontsize=12)
    ax.set_ylabel('Jumlah Tweet', fontsize=12)
    ax.legend(['Negatif', 'Positif'], fontsize=11)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.tick_params(axis='x', rotation=45)
    plt.tight_layout()
    plt.savefig('time_series_sentimen.png', dpi=300, bbox_inches='tight')
    plt.show()

    print("✅ Time series disimpan: time_series_sentimen.png")
else:
    print("\n⚠️ Kolom 'created_at' tidak tersedia untuk time series")

# =====================================================
# 11. WORDCLOUD
# =====================================================
print("\n" + "=" * 70)
print("WORDCLOUD")
print("=" * 70)

# -----------------------------------------------------
# [BARU] Filter Kata 'Cerai' dari Teks
# -----------------------------------------------------
# 1. Gabungkan semua teks
all_words = ' '.join(df['preprocessed_text'])

# 2. Hapus kata 'cerai' (case-insensitive)
all_words_filtered = all_words.replace('cerai', '').replace('Cerai', '').replace('CERAI', '')

# 3. Bersihkan spasi ganda yang mungkin muncul
import re
all_words_filtered = re.sub(r'\s+', ' ', all_words_filtered).strip()

# 4. Generate WordCloud dengan teks yang sudah difilter
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white',
    max_words=200,
    colormap='viridis'
).generate(all_words_filtered)

# -----------------------------------------------------
# [BARU] Tampilkan Statistik Kata yang Dihapus
# -----------------------------------------------------
cerai_count = all_words.lower().count('cerai')
print(f"\n📊 Kata 'cerai' ditemukan: {cerai_count} kali")
print(f"✅ Kata 'cerai' telah dihapus dari WordCloud")

# -----------------------------------------------------
# [ASLI] Plot WordCloud
# -----------------------------------------------------
plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('WordCloud Sentimen Publik (Tanpa Kata "Cerai")', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig('wordcloud_sentimen.png', dpi=300, bbox_inches='tight')
plt.show()

print("✅ WordCloud disimpan: wordcloud_sentimen.png")
# =====================================================
# 12. SIMPAN MODEL
# =====================================================
print("\n" + "=" * 70)
print("SIMPAN MODEL")
print("=" * 70)

with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(pipeline_mnb.named_steps['tfidf'], f)

with open('naive_bayes_model.pkl', 'wb') as f:
    pickle.dump(pipeline_mnb.named_steps['nb'], f)

print("✅ Model MultinomialNB disimpan:")
print("   - tfidf_vectorizer.pkl")
print("   - naive_bayes_model.pkl")